In [1]:
#Importing Dependencies
import pandas as pd
from sqlalchemy import create_engine

In [3]:
csv_file = "./Government Education.csv"
original_csv_df = pd.read_csv(csv_file)
original_csv_df.head()

,Country,Region,Happiness Rank,Happiness Score,Lower Confidence Interval,Upper Confidence Interval,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Denmark,Western Europe,1,7.526,7.460,7.592,1.44178,1.16374,0.79504,0.57941,0.44453,0.36171,2.73939
1,Switzerland,Western Europe,2,7.509,7.428,7.590,1.52733,1.14524,0.86303,0.58557,0.41203,0.28083,2.69463
2,Iceland,Western Europe,3,7.501,7.333,7.669,1.42666,1.18326,0.86733,0.56624,0.14975,0.47678,2.83137
3,Norway,Western Europe,4,7.498,7.421,7.575,1.57744,1.12690,0.79579,0.59609,0.35776,0.37895,2.66465
4,Finland,Western Europe,5,7.413,7.351,7.475,1.40598,1.13464,0.81091,0.57104,0.41004,0.25492,2.82596

In [16]:
#Select columns needed
updated_csv_df = original_csv_df[["Country", "Happiness Rank", "Happiness Score", "Trust (Government Corruption)", "Economy (GDP per Capita)"]].copy()
updated_csv_df

,Country,Happiness Rank,Happiness Score,Trust (Government Corruption),Economy (GDP per Capita)
0,Denmark,1,7.526,0.44453,1.44178
1,Switzerland,2,7.509,0.41203,1.52733
2,Iceland,3,7.501,0.14975,1.42666
3,Norway,4,7.498,0.35776,1.57744
4,Finland,5,7.413,0.41004,1.40598
5,Canada,6,7.404,0.31329,1.44015
6,Netherlands,7,7.339,0.29927,1.46468
7,New Zealand,8,7.334,0.41904,1.36066
8,Australia,9,7.313,0.32331,1.44443
9,Sweden,10,7.291,0.40867,1.45181
10,Israel,11,7.267,0.08728,1.33766
11,Austria,12,7.119,0.21348,1.45038
12,United States,13,7.104,0.14868,1.50796
13,Costa Rica,14,7.087,0.10547,1.06879
14,Puerto Rico,15,7.039,0.12275,1.35943
15,Germany,16,6.994,0.28551,1.44787
16,Brazil,17,6.952,0.14166,1.08754
17,Belgium,18,6.929,0.26248,1.42539
18,Ireland,19,6.907,0.29754,1.48341
19,Luxembourg,20,6.871,0.35329,1.69752
20,Mexico,21,6.778,0.18355,1.11508
21,Singapore,22,6.739,0.46987,1.64555
22,United Kingdom,23,6.725,0.27399,1.40283
23,Chile,24,6.705,0.11451,1.21670
24,Panama,25,6.701,0.08423,1.18306
25,Argentina,26,6.650,0.07296,1.15137
26,Czech Republic,27,6.596,0.03986,1.30915
27,United Arab Emirates,28,6.573,0.35561,1.57352
28,Uruguay,29,6.545,0.21394,1.18157
29,Malta,30,6.488,0.17554,1.30782
...,...,...,...,...,...
127,Senegal,128,4.219,0.11681,0.44314
128,Bulgaria,129,4.217,0.00615,1.11306
129,Mauritania,130,4.201,0.17955,0.61391
130,Zimbabwe,131,4.193,0.08582,0.35041
131,Malawi,132,4.156,0.07564,0.08709
132,Sudan,133,4.139,0.10039,0.63069
133,Gabon,134,4.121,0.09314,1.15851
134,Mali,135,4.073,0.13647,0.31292
135,Haiti,136,4.028,0.14476,0.34097
136,Botswana,137,3.974,0.10769,1.09426
137,Comoros,138,3.956,0.18437,0.27509
138,Ivory Coast,139,3.916,0.15530,0.55507
139,Cambodia,140,3.907,0.08092,0.55604
140,Angola,141,3.866,0.08434,0.84731
141,Niger,142,3.856,0.17176,0.13270
142,South Sudan,143,3.832,0.13015,0.39394
143,Chad,144,3.763,0.04952,0.42214
144,Burkina Faso,145,3.739,0.12533,0.31995
145,Uganda,145,3.739,0.06442,0.34719
146,Yemen,147,3.724,0.05892,0.57939
147,Madagascar,148,3.695,0.07506,0.27954
148,Tanzania,149,3.666,0.05099,0.47155
149,Liberia,150,3.622,0.04852,0.10706
150,Guinea,151,3.607,0.11920,0.22415
151,Rwanda,152,3.515,0.50521,0.32846
152,Benin,153,3.484,0.06681,0.39499
153,Afghanistan,154,3.360,0.07112,0.38227
154,Togo,155,3.303,0.11587,0.28123
155,Syria,156,3.069,0.17233,0.74719
156,Burundi,157,2.905,0.09419,0.06831

In [24]:
final_csv_df = updated_csv_df.rename(columns = {"Country":"Country_Name", "Happiness Rank":"Happiness_Rank",\
                                 "Happiness Score":"Happiness_Score","Trust (Government Corruption)":"Trust_Government_Corruption",\
                                 "Economy (GDP per Capita)":"Economy_GDP_Per_Capita"})

final_csv_df.head()

,Country_Name,Happiness_Rank,Happiness_Score,Trust_Government_Corruption,Economy_GDP_Per_Capita
0,Denmark,1,7.526,0.44453,1.44178
1,Switzerland,2,7.509,0.41203,1.52733
2,Iceland,3,7.501,0.14975,1.42666
3,Norway,4,7.498,0.35776,1.57744
4,Finland,5,7.413,0.41004,1.40598

In [25]:
engine = create_engine("mysql+mysqlconnector://root:Js@lguer0@localhost/happiness_indicators_2016")

In [26]:
engine.table_names()

['world_happiness_report']

In [27]:
final_csv_df.to_sql(name='world_happiness_report', con=engine, if_exists='append', index=False)